name: Cleanup Old GHCR Container Images

on:
  schedule:
    - cron: '30 3 * * 0'   # weekly, Sunday 03:30 UTC
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up old images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          owner: ${{ github.repository_owner }}
          package: ${{ github.event.repository.name }}

          exclude-tags: 'latest,dev,staging,unstable,pix-lgbt,stable,v*.*.*'
          older-than: 6 months
          delete-untagged: true
          keep-n-tagged: 25
